//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinHangWisdomParkWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbConfirmState
    {
        public int ApplyID { get; set; }
        public Nullable<int> CurrConfirmLevel { get; set; }
        public Nullable<int> NeedConfirmLevel { get; set; }
        public string ConfirmerID1 { get; set; }
        public Nullable<System.DateTime> ConfirmerDate1 { get; set; }
        public string ConfirmerID2 { get; set; }
        public Nullable<System.DateTime> ConfirmerDate2 { get; set; }
        public string ConfirmerID3 { get; set; }
        public Nullable<System.DateTime> ConfirmerDate3 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
